cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost}

management:
    endpoint:
        health:
            show-details: always

server:
    error:
        include-message: always
    port: 8080

spring:
  application:
    name: upcoming-movies-api
